### ISSUE TITLE
Sorting by ctime

### ISSUE THREAD

**Issue by inseldesign** [nirebu/nirebu-2019#1]
Hej Nicolo,

just tried your way how to render markdown with nuxt js. Everything works as expected but sorting is somehow not working. It does not show the last added article (date taken by ctime). What could be the reason?  Thank you

**Comment by nirebu** [comment]
Hi Sascha,

sorry for getting back so late, when you opened the issue I was undergoing surgery. Back to the core problem now... Can you provide a couple of example? Like the dates used or the frontmatter of the markdown files?

Thank you

**Comment by inseldesign** [comment]
I just cloned your repo and added some more articles with dates in the past. But articles were not sorted from latest date to newest. Even if I change something in the store index.js the articles order will not change.

**Comment by inseldesign** [comment]
Date format was the same as yours

**Comment by inseldesign** [comment]
This thread still alive? @nirebu

**Comment by nirebu** [comment]
Yup, I'm sorry for getting back so late. I think that bb08f4d should fix the issue. Can you try it out?

**Comment by inseldesign** [comment]
Ah yeah, this did the trick. Thank you!
